spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: card-service
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/card/**
        - id: query-service
          uri: lb://QUERY-SERVICE
          predicates:
            - Path=/query/**
        - id: translate-service
          uri: lb://TRANSLATE-SERVICE
          predicates:
            - Path=/translate/**
server:
  port: 8989
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost