server:
  port: 8090
spring:
  application:
    name: TRANSLATE-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

